// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: drawing_service.proto
#ifndef GRPC_drawing_5fservice_2eproto__INCLUDED
#define GRPC_drawing_5fservice_2eproto__INCLUDED

#include "drawing_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace Whiteboard {
namespace Drawing {

class DrawingService final {
 public:
  static constexpr char const* service_full_name() {
    return "Whiteboard.Drawing.DrawingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> OpenDrawingStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(OpenDrawingStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> AsyncOpenDrawingStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(AsyncOpenDrawingStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> PrepareAsyncOpenDrawingStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(PrepareAsyncOpenDrawingStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void OpenDrawingStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::Whiteboard::Drawing::StreamEvent,::Whiteboard::Drawing::StreamEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* OpenDrawingStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* AsyncOpenDrawingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* PrepareAsyncOpenDrawingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> OpenDrawingStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(OpenDrawingStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> AsyncOpenDrawingStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(AsyncOpenDrawingStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>> PrepareAsyncOpenDrawingStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>>(PrepareAsyncOpenDrawingStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OpenDrawingStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::Whiteboard::Drawing::StreamEvent,::Whiteboard::Drawing::StreamEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* OpenDrawingStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* AsyncOpenDrawingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* PrepareAsyncOpenDrawingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OpenDrawingStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OpenDrawingStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_OpenDrawingStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OpenDrawingStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OpenDrawingStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDrawingStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenDrawingStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OpenDrawingStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OpenDrawingStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OpenDrawingStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->OpenDrawingStream(context); }));
    }
    ~WithCallbackMethod_OpenDrawingStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDrawingStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* OpenDrawingStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_OpenDrawingStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OpenDrawingStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OpenDrawingStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OpenDrawingStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDrawingStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OpenDrawingStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OpenDrawingStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OpenDrawingStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDrawingStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenDrawingStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OpenDrawingStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OpenDrawingStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->OpenDrawingStream(context); }));
    }
    ~WithRawCallbackMethod_OpenDrawingStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDrawingStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::Whiteboard::Drawing::StreamEvent, ::Whiteboard::Drawing::StreamEvent>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* OpenDrawingStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace Drawing
}  // namespace Whiteboard


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_drawing_5fservice_2eproto__INCLUDED
