// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_connection.proto
#ifndef GRPC_server_5fconnection_2eproto__INCLUDED
#define GRPC_server_5fconnection_2eproto__INCLUDED

#include "server_connection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace Whiteboard {
namespace Server {

class ServerConnectionService final {
 public:
  static constexpr char const* service_full_name() {
    return "Whiteboard.Server.ServerConnectionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::Whiteboard::Server::ServerConnectionConfirmation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>> AsyncConnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>>(AsyncConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>> PrepareAsyncConnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>>(PrepareAsyncConnectRaw(context, request, cq));
    }
    virtual ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::Whiteboard::Server::ServerConnectionConfirmation* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>> AsyncDisconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>* AsyncConnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>* PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Whiteboard::Server::ServerConnectionConfirmation>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::Whiteboard::Server::ServerConnectionConfirmation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>> AsyncConnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>>(AsyncConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>> PrepareAsyncConnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>>(PrepareAsyncConnectRaw(context, request, cq));
    }
    ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::Whiteboard::Server::ServerConnectionConfirmation* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>> AsyncDisconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, std::function<void(::grpc::Status)>) override;
      void Connect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, std::function<void(::grpc::Status)>) override;
      void Disconnect(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>* AsyncConnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>* PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Whiteboard::Server::ServerConnectionConfirmation>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::Whiteboard::Server::ServerConnectionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Connect_;
    const ::grpc::internal::RpcMethod rpcmethod_Disconnect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Connect(::grpc::ServerContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response);
    virtual ::grpc::Status Disconnect(::grpc::ServerContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Connect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnect(::grpc::ServerContext* context, ::Whiteboard::Server::ServerConnectionRequest* request, ::grpc::ServerAsyncResponseWriter< ::Whiteboard::Server::ServerConnectionConfirmation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Disconnect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::Whiteboard::Server::ServerConnectionRequest* request, ::grpc::ServerAsyncResponseWriter< ::Whiteboard::Server::ServerConnectionConfirmation>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Connect<WithAsyncMethod_Disconnect<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Connect() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response) { return this->Connect(context, request, response); }));}
    void SetMessageAllocatorFor_Connect(
        ::grpc::MessageAllocator< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Connect(
      ::grpc::CallbackServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Whiteboard::Server::ServerConnectionRequest* request, ::Whiteboard::Server::ServerConnectionConfirmation* response) { return this->Disconnect(context, request, response); }));}
    void SetMessageAllocatorFor_Disconnect(
        ::grpc::MessageAllocator< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Connect<WithCallbackMethod_Disconnect<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Connect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Disconnect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Connect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Disconnect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Connect() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Connect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Connect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Disconnect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Connect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>* streamer) {
                       return this->StreamedConnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Whiteboard::Server::ServerConnectionRequest,::Whiteboard::Server::ServerConnectionConfirmation>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Disconnect() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Whiteboard::Server::ServerConnectionRequest, ::Whiteboard::Server::ServerConnectionConfirmation>* streamer) {
                       return this->StreamedDisconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::Whiteboard::Server::ServerConnectionRequest* /*request*/, ::Whiteboard::Server::ServerConnectionConfirmation* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDisconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Whiteboard::Server::ServerConnectionRequest,::Whiteboard::Server::ServerConnectionConfirmation>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Connect<WithStreamedUnaryMethod_Disconnect<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Connect<WithStreamedUnaryMethod_Disconnect<Service > > StreamedService;
};

}  // namespace Server
}  // namespace Whiteboard


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_server_5fconnection_2eproto__INCLUDED
