// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: server_connection.proto
// Protobuf C++ Version: 6.30.0

#include "server_connection.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Whiteboard {
namespace Server {

inline constexpr ServerConnectionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        connection_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerConnectionRequest::ServerConnectionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ServerConnectionRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServerConnectionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerConnectionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerConnectionRequestDefaultTypeInternal() {}
  union {
    ServerConnectionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerConnectionRequestDefaultTypeInternal _ServerConnectionRequest_default_instance_;

inline constexpr ServerConnectionConfirmation::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        connection_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerConnectionConfirmation::ServerConnectionConfirmation(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ServerConnectionConfirmation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServerConnectionConfirmationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerConnectionConfirmationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerConnectionConfirmationDefaultTypeInternal() {}
  union {
    ServerConnectionConfirmation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerConnectionConfirmationDefaultTypeInternal _ServerConnectionConfirmation_default_instance_;
}  // namespace Server
}  // namespace Whiteboard
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_server_5fconnection_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_server_5fconnection_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_5fconnection_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionRequest, _impl_.connection_),
        0,
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionConfirmation, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionConfirmation, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Whiteboard::Server::ServerConnectionConfirmation, _impl_.connection_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::Whiteboard::Server::ServerConnectionRequest)},
        {10, 19, -1, sizeof(::Whiteboard::Server::ServerConnectionConfirmation)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Whiteboard::Server::_ServerConnectionRequest_default_instance_._instance,
    &::Whiteboard::Server::_ServerConnectionConfirmation_default_instance_._instance,
};
const char descriptor_table_protodef_server_5fconnection_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027server_connection.proto\022\021Whiteboard.Se"
    "rver\"-\n\027ServerConnectionRequest\022\022\n\nconne"
    "ction\030\001 \001(\005\"2\n\034ServerConnectionConfirmat"
    "ion\022\022\n\nconnection\030\001 \001(\0052\201\001\n\027ServerConnec"
    "tionService\022f\n\007Connect\022*.Whiteboard.Serv"
    "er.ServerConnectionRequest\032/.Whiteboard."
    "Server.ServerConnectionConfirmationb\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_server_5fconnection_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_server_5fconnection_2eproto = {
    false,
    false,
    283,
    descriptor_table_protodef_server_5fconnection_2eproto,
    "server_connection.proto",
    &descriptor_table_server_5fconnection_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_server_5fconnection_2eproto::offsets,
    file_level_enum_descriptors_server_5fconnection_2eproto,
    file_level_service_descriptors_server_5fconnection_2eproto,
};
namespace Whiteboard {
namespace Server {
// ===================================================================

class ServerConnectionRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ServerConnectionRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ServerConnectionRequest, _impl_._has_bits_);
};

ServerConnectionRequest::ServerConnectionRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServerConnectionRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Whiteboard.Server.ServerConnectionRequest)
}
ServerConnectionRequest::ServerConnectionRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ServerConnectionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServerConnectionRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ServerConnectionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ServerConnectionRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.connection_ = {};
}
ServerConnectionRequest::~ServerConnectionRequest() {
  // @@protoc_insertion_point(destructor:Whiteboard.Server.ServerConnectionRequest)
  SharedDtor(*this);
}
inline void ServerConnectionRequest::SharedDtor(MessageLite& self) {
  ServerConnectionRequest& this_ = static_cast<ServerConnectionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ServerConnectionRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ServerConnectionRequest(arena);
}
constexpr auto ServerConnectionRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ServerConnectionRequest),
                                            alignof(ServerConnectionRequest));
}
constexpr auto ServerConnectionRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ServerConnectionRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ServerConnectionRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ServerConnectionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ServerConnectionRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ServerConnectionRequest>(), &ServerConnectionRequest::ByteSizeLong,
              &ServerConnectionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ServerConnectionRequest, _impl_._cached_size_),
          false,
      },
      &ServerConnectionRequest::kDescriptorMethods,
      &descriptor_table_server_5fconnection_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ServerConnectionRequest_class_data_ =
            ServerConnectionRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ServerConnectionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ServerConnectionRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ServerConnectionRequest_class_data_.tc_table);
  return ServerConnectionRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ServerConnectionRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ServerConnectionRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ServerConnectionRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Whiteboard::Server::ServerConnectionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 connection = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServerConnectionRequest, _impl_.connection_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(ServerConnectionRequest, _impl_.connection_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 connection = 1;
    {PROTOBUF_FIELD_OFFSET(ServerConnectionRequest, _impl_.connection_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ServerConnectionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Whiteboard.Server.ServerConnectionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.connection_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ServerConnectionRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ServerConnectionRequest& this_ = static_cast<const ServerConnectionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ServerConnectionRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ServerConnectionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Whiteboard.Server.ServerConnectionRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 connection = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_connection() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_connection(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Whiteboard.Server.ServerConnectionRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ServerConnectionRequest::ByteSizeLong(const MessageLite& base) {
  const ServerConnectionRequest& this_ = static_cast<const ServerConnectionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ServerConnectionRequest::ByteSizeLong() const {
  const ServerConnectionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Whiteboard.Server.ServerConnectionRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 connection = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_connection() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_connection());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ServerConnectionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServerConnectionRequest*>(&to_msg);
  auto& from = static_cast<const ServerConnectionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Whiteboard.Server.ServerConnectionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_connection() != 0) {
      _this->_impl_.connection_ = from._impl_.connection_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerConnectionRequest::CopyFrom(const ServerConnectionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Whiteboard.Server.ServerConnectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ServerConnectionRequest::InternalSwap(ServerConnectionRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.connection_, other->_impl_.connection_);
}

::google::protobuf::Metadata ServerConnectionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ServerConnectionConfirmation::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ServerConnectionConfirmation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ServerConnectionConfirmation, _impl_._has_bits_);
};

ServerConnectionConfirmation::ServerConnectionConfirmation(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServerConnectionConfirmation_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Whiteboard.Server.ServerConnectionConfirmation)
}
ServerConnectionConfirmation::ServerConnectionConfirmation(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ServerConnectionConfirmation& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServerConnectionConfirmation_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ServerConnectionConfirmation::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ServerConnectionConfirmation::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.connection_ = {};
}
ServerConnectionConfirmation::~ServerConnectionConfirmation() {
  // @@protoc_insertion_point(destructor:Whiteboard.Server.ServerConnectionConfirmation)
  SharedDtor(*this);
}
inline void ServerConnectionConfirmation::SharedDtor(MessageLite& self) {
  ServerConnectionConfirmation& this_ = static_cast<ServerConnectionConfirmation&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ServerConnectionConfirmation::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ServerConnectionConfirmation(arena);
}
constexpr auto ServerConnectionConfirmation::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ServerConnectionConfirmation),
                                            alignof(ServerConnectionConfirmation));
}
constexpr auto ServerConnectionConfirmation::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ServerConnectionConfirmation_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ServerConnectionConfirmation::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ServerConnectionConfirmation>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ServerConnectionConfirmation::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ServerConnectionConfirmation>(), &ServerConnectionConfirmation::ByteSizeLong,
              &ServerConnectionConfirmation::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ServerConnectionConfirmation, _impl_._cached_size_),
          false,
      },
      &ServerConnectionConfirmation::kDescriptorMethods,
      &descriptor_table_server_5fconnection_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ServerConnectionConfirmation_class_data_ =
            ServerConnectionConfirmation::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ServerConnectionConfirmation::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ServerConnectionConfirmation_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ServerConnectionConfirmation_class_data_.tc_table);
  return ServerConnectionConfirmation_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ServerConnectionConfirmation::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ServerConnectionConfirmation, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ServerConnectionConfirmation_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Whiteboard::Server::ServerConnectionConfirmation>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 connection = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServerConnectionConfirmation, _impl_.connection_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(ServerConnectionConfirmation, _impl_.connection_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 connection = 1;
    {PROTOBUF_FIELD_OFFSET(ServerConnectionConfirmation, _impl_.connection_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ServerConnectionConfirmation::Clear() {
// @@protoc_insertion_point(message_clear_start:Whiteboard.Server.ServerConnectionConfirmation)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.connection_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ServerConnectionConfirmation::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ServerConnectionConfirmation& this_ = static_cast<const ServerConnectionConfirmation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ServerConnectionConfirmation::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ServerConnectionConfirmation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:Whiteboard.Server.ServerConnectionConfirmation)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 connection = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_connection() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_connection(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Whiteboard.Server.ServerConnectionConfirmation)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ServerConnectionConfirmation::ByteSizeLong(const MessageLite& base) {
  const ServerConnectionConfirmation& this_ = static_cast<const ServerConnectionConfirmation&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ServerConnectionConfirmation::ByteSizeLong() const {
  const ServerConnectionConfirmation& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Whiteboard.Server.ServerConnectionConfirmation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 connection = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_connection() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_connection());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ServerConnectionConfirmation::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServerConnectionConfirmation*>(&to_msg);
  auto& from = static_cast<const ServerConnectionConfirmation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Whiteboard.Server.ServerConnectionConfirmation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_connection() != 0) {
      _this->_impl_.connection_ = from._impl_.connection_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerConnectionConfirmation::CopyFrom(const ServerConnectionConfirmation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Whiteboard.Server.ServerConnectionConfirmation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ServerConnectionConfirmation::InternalSwap(ServerConnectionConfirmation* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.connection_, other->_impl_.connection_);
}

::google::protobuf::Metadata ServerConnectionConfirmation::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Server
}  // namespace Whiteboard
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_server_5fconnection_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
