message(STATUS "${proj}.cmake with CMAKE_BUILD_TYPE:'${CMAKE_BUILD_TYPE}'")

if(NOT TARGET download-${proj})
  ExternalProject_Add(download-${proj}
    DOWNLOAD_DIR ${DOWNLOAD_DIR}
    URL ${${proj}_url}
    URL_MD5 ${${proj}_md5}
    DOWNLOAD_EXTRACT_TIMESTAMP FALSE
    SOURCE_DIR ${SOURCE_DIR}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )
endif()

ExternalProject_Add(${proj}${CMAKE_BUILD_TYPE}
  DOWNLOAD_COMMAND ""
  DOWNLOAD_EXTRACT_TIMESTAMP FALSE
  SOURCE_DIR ${SOURCE_DIR}
  BINARY_DIR ${BINARY_DIR}
  INSTALL_DIR ${INSTALL_DIR}
  CMAKE_ARGS
    # generic args
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}
    -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
    -DCMAKE_CXX_STANDARD:STRING=17
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    # project specific args for re2
    -DCMAKE_POLICY_DEFAULT_CMP0091=NEW # without this, re2 doesn't adhere to runtime library and config
    -DRE2_BUILD_TESTING:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  DEPENDS protobuf${CMAKE_BUILD_TYPE}
  UPDATE_COMMAND ""
)
